[project]
name = "super-bryn"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "livekit-agents[groq,silero,turn-detector]~=1.3",
    "livekit-plugins-groq>=1.4.1",
    "livekit-plugins-noise-cancellation~=0.2",
    "onnxruntime<1.19.0",
    "python-dotenv>=1.2.1",
]
